export enum WebAPIException {
  INDEX_SIZE_ERR = 1,
  DOMSTRING_SIZE_ERR = 2,
  HIERARCHY_REQUEST_ERR = 3,
  WRONG_DOCUMENT_ERR = 4,
  INVALID_CHARACTER_ERR = 5,
  NO_DATA_ALLOWED_ERR = 6,
  NO_MODIFICATION_ALLOWED_ERR = 7,
  NOT_FOUND_ERR = 8,
  NOT_SUPPORTED_ERR = 9,
  INUSE_ATTRIBUTE_ERR = 10,
  INVALID_STATE_ERR = 11,
  SYNTAX_ERR = 12,
  INVALID_MODIFICATION_ERR = 13,
  NAMESPACE_ERR = 14,
  INVALID_ACCESS_ERR = 15,
  VALIDATION_ERR = 16,
  TYPE_MISMATCH_ERR = 17,
  SECURITY_ERR = 18,
  NETWORK_ERR = 19,
  ABORT_ERR = 20,
  URL_MISMATCH_ERR = 21,
  QUOTA_EXCEEDED_ERR = 22,
  TIMEOUT_ERR = 23,
  INVALID_NODE_TYPE_ERR = 24,
  DATA_CLONE_ERR = 25,
  INVALID_VALUES_ERR = 26,
  IO_ERR = 27,
  SERVICE_NOT_AVAILABLE_ERR = 28,
  UNKNOWN_ERR = 9999
}

export enum AVPlayPlayerState {
  NONE = 'NONE',
  IDLE = 'IDLE',
  READY = 'READY',
  PLAYING = 'PLAYING',
  PAUSED = 'PAUSED'
}

export enum AVPlayDisplayMode {
  PLAYER_DISPLAY_MODE_LETTER_BOX = 'PLAYER_DISPLAY_MODE_LETTER_BOX',
  PLAYER_DISPLAY_MODE_FULL_SCREEN = 'PLAYER_DISPLAY_MODE_FULL_SCREEN',
  PLAYER_DISPLAY_MODE_AUTO_ASPECT_RATIO = 'PLAYER_DISPLAY_MODE_AUTO_ASPECT_RATIO'
}

export enum AVPlayBufferOption {
  PLAYER_BUFFER_FOR_PLAY = 'PLAYER_BUFFER_FOR_PLAY',
  PLAYER_BUFFER_FOR_RESUME = 'PLAYER_BUFFER_FOR_RESUME'
}

export enum AVPlayBufferSizeUnit {
  PLAYER_BUFFER_SIZE_IN_BYTE = 'PLAYER_BUFFER_SIZE_IN_BYTE',
  PLAYER_BUFFER_SIZE_IN_SECOND = 'PLAYER_BUFFER_SIZE_IN_SECOND'
}

export enum AVPlayStreamingPropertyType {
  COOKIE = 'COOKIE',
  USER_AGENT = 'USER_AGENT',
  PREBUFFER_MODE = 'PREBUFFER_MODE',
  ADAPTIVE_INFO = 'ADAPTIVE_INFO',
  SET_MODE_4K = 'SET_MODE_4K',
  PROPERTY_HD_AUDIO = 'PROPERTY_HD_AUDIO',
  LISTEN_SPARSE_TRACK = 'LISTEN_SPARSE_TRACK',
  IS_LIVE = 'IS_LIVE',
  AVAILABLE_BITRATE = 'AVAILABLE_BITRATE',
  GET_LIVE_DURATION = 'GET_LIVE_DURATION',
  CURRENT_BANDWIDTH = 'CURRENT_BANDWIDTH',
  WIDEVINE = 'WIDEVINE'
}

export enum AVPlayDrmType {
  PLAYREADY = 'PLAYREADY',
  VERIMATRIX = 'VERIMATRIX',
  WIDEVINE_CDM = 'WIDEVINE_CDM'
}

export enum AVPlayDrmOperation {
  SetProperties = 'SetProperties',
  InstallLicense = 'InstallLicense',
  ProcessInitiator = 'ProcessInitiator',
  GetUID = 'GetUID',
  Initialize = 'Initialize',
  Finalize = 'Finalize',
  widevine_license_data = 'widevine_license_data',
  widevine_app_session = 'widevine_app_session',
  widevine_data_type = 'widevine_data_type'
}

export enum AVPlayStreamType {
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  TEXT = 'TEXT'
}

export enum AVPlayError {
  PLAYER_ERROR_NONE = 'PLAYER_ERROR_NONE',
  PLAYER_ERROR_INVALID_PARAMETER = 'PLAYER_ERROR_INVALID_PARAMETER',
  PLAYER_ERROR_NO_SUCH_FILE = 'PLAYER_ERROR_NO_SUCH_FILE',
  PLAYER_ERROR_INVALID_OPERATION = 'PLAYER_ERROR_INVALID_OPERATION',
  PLAYER_ERROR_SEEK_FAILED = 'PLAYER_ERROR_SEEK_FAILED',
  PLAYER_ERROR_INVALID_STATE = 'PLAYER_ERROR_INVALID_STATE',
  PLAYER_ERROR_NOT_SUPPORTED_FILE = 'PLAYER_ERROR_NOT_SUPPORTED_FILE',
  PLAYER_ERROR_INVALID_URI = 'PLAYER_ERROR_INVALID_URI',
  PLAYER_ERROR_CONNECTION_FAILED = 'PLAYER_ERROR_CONNECTION_FAILED',
  PLAYER_ERROR_GENEREIC = 'PLAYER_ERROR_GENEREIC'
}

export enum AVPlayEvent {
  PLAYER_MSG_NONE = 'PLAYER_MSG_NONE',
  PLAYER_MSG_RESOLUTION_CHANGED = 'PLAYER_MSG_RESOLUTION_CHANGED',
  PLAYER_MSG_BITRATE_CHANGE = 'PLAYER_MSG_BITRATE_CHANGE',
  PLAYER_MSG_FRAGMENT_INFO = 'PLAYER_MSG_FRAGMENT_INFO',
  PLAYER_SPARSE_TRACK_DETECT = 'PLAYER_SPARSE_TRACK_DETECT',
  PLAYER_STREAMING_EVENT = 'PLAYER_STREAMING_EVENT',
  PLAYER_MSG_HTTP_ERROR_CODE = 'PLAYER_MSG_HTTP_ERROR_CODE',
  PLAYER_MSG_DRM_CHALLENGE_DATA = 'PLAYER_MSG_DRM_CHALLENGE_DATA'
}


export enum AppCommonKeyName {
  SmartHub = 10071,
  Power = 409,
  SMODE = 10197,
  PMODE = 10141,
  More = 10148,
  BTVoice = 10224,
  Color = 10385,
  BTPairing = 10161,
  Sleep = 10150,
  Netflix = 10234,
  NoiseReduction = 10519,
  Help = 10520,
  Content = 10497,
  HotelMovies = 10494,
  HotelLanguage = 10495,
  HotelTVGuide = 10496,
  NR = 10521,
  HotelRoomControl = 10522,
  Ambient = 10530,
  PanelPower = 10531,
  PanelSource = 10532,
  PanelMenu = 10533
}

export enum AppCommonScreenSaverState {
  SCREEN_SAVER_OFF = 0,
  SCREEN_SAVER_ON = 1
}

export enum AppCommonRecommendedWordsType {
  RECOMMENDED_WORDS_DISABLE = 0,
  RECOMMENDED_WORDS_ENABLE = 1
}
export enum AppcommonTarget {
  CONFIG_LAST_SOURCE = 0
}

export enum AppcommonAction {
  CONFIG_LAUNCH = 0
}